include:
  - component: gitlab.com/gitlab-org/components/gem-release/gem-release@~latest

default:
  image: "ruby:${RUBY_VERSION}"

cache:
  paths:
    - vendor/ruby

before_script:
  - ruby -v
  - bundle install -j $(nproc) --path vendor

test:
  script:
    - bundle exec rake test
  parallel:
    matrix:
      - RUBY_VERSION: [ "2.7", "3.0", "3.1", "3.2" ]

rubocop:
  script:
    - bundle exec rubocop
  variables:
    RUBY_VERSION: "3.1"

integration:
  services:
    - alias: azurite
      name: mcr.microsoft.com/azure-storage/azurite
  script:
    - bundle exec rake integration
  variables:
    RUBY_VERSION: "3.2"
